# auto generated resource file. WARNING: do not edit
from PyQt4 import QtCore
_cache = {}
def hotkeys():
	arr = _cache.get("hotkeys", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5Ib3RrZXlzPC9kaXY+CgoJPGRpdiBjbGFzcz0ibm90ZUJveCI+Tm90ZTogdGhpcyBhbmQgdGhhdDwvZGl2PgoKPC9kaXY+CgoKCgoKPC9ib2R5PjwvaHRtbD4KCg==")
		_cache["hotkeys"] = arr
	return QtCore.QString(arr)
def hotkeyAlterBetAmount():
	arr = _cache.get("hotkeyAlterBetAmount", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("SG90a2V5QWx0ZXJCZXRBbW91bnQ=")
		_cache["hotkeyAlterBetAmount"] = arr
	return QtCore.QString(arr)
def hand():
	arr = _cache.get("hand", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5IYW5kPC9kaXY+CgoJVGhpcyB0YWIgaXMgYSBiaXQgc3BlY2lhbC4gYmVoaW5kIHRoZSBzY2VlbmVkcyB0aGVyZSBpcyBhIGdyYWJiZXIgcnVubmluZyB0aGF0IHdpbGwgY2hlY2sgaWYgUG9rZXJTdGFycyBJbnN0YW50SGFuZEhpc3RvcnkgZGlhbG9nIGlzIG9wZW4uIGlmIHNvLCB0aGUgY3VycmVudGx5IHNlbGVjdGVkCgloYW5kIGlzIGR1bXBlZCBuaWNlbHkgZm9ybWF0dGVkIHRvIHRoaXMgdGFiLiBiZXN0IHVzZSBhbG9uZyB3aXRoIHRoZSAgPGEgaHJlZj0iaG90a2V5SW5zdGFudEhhbmRIaXN0b3J5Lmh0bWwiPkluc3RhbnRIYW5kSGlzdG9yeTwvYT4gaG90a2V5IGFzIGEgcmVwbGFjZW1lbnQKCWZvciBQb2tlclN0YXJzIHJlcGxheWVyLgoJCgkKCTxkaXYgY2xhc3M9Im5vdGVCb3giPgoJCTx1bD4KCQk8bGk+dGhlIGdyYWJiZXIgb25seSB3b3JrcyBmb3IgVGV4YXMgSG9sZCdlbSBhbmQgT21haGEgKG5sL3BsKQoJCTwvdWw+Cgk8L2Rpdj4KCjwvZGl2PgoKCgoKCjwvYm9keT48L2h0bWw+")
		_cache["hand"] = arr
	return QtCore.QString(arr)
def hotkeyReplayer():
	arr = _cache.get("hotkeyReplayer", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("SG90a2V5UmVwbGF5ZXI=")
		_cache["hotkeyReplayer"] = arr
	return QtCore.QString(arr)
def hotkeyRaise():
	arr = _cache.get("hotkeyRaise", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5Ib3RrZXkgUmFpc2U8L2Rpdj4KCgl3aGVuZXZlciB5b3UgaGl0IHRoaXMga2V5IFRhYmxlQ3JhYiB3aWxsIHJhaXNlIHRoZSBoYW5kIGZvciB5b3UuIHRoYXQgaXMgLSBpdCBlaXRoZXIgaGl0cyB0aGUgPGk+IlJhaXNlL0NhbGwiPC9pPiBidXR0b24uCgkKPC9kaXY+CgoKPC9ib2R5PjwvaHRtbD4=")
		_cache["hotkeyRaise"] = arr
	return QtCore.QString(arr)
def settingsHand():
	arr = _cache.get("settingsHand", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("U2V0dGluZ3NIYW5kCg==")
		_cache["settingsHand"] = arr
	return QtCore.QString(arr)
def index():
	arr = _cache.get("index", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5UYWJsZUNyYWIgLSBQb2tlclN0YXJzIGhvdGtleXMgYW5kIG1vcmU8L2Rpdj4KCglXZWxjb21lIHRvIFRhYmxlQ3JhYi4gVGFibGVDcmFiIGlzIGEgc2ltcGxlIGhvdGtleSBtYW5hZ2VyIGZvciBQb2tlclN0YXJzIGFuZCBzb21lIGV4dHJhcy4KCQoJPHVsPgoJCTxsaT5pdCBpcyBkZXZlbG9wZWQgYW5kIHRlc3RlZCBvbiBsaW51eCBhbmQgdGh1cyBydW5zIG9uIHdpbmUKCQk8bGk+aXQgaXMgdGVzdGVkIG9uIHdpbmRvd3NYUAoJCTxsaT5pdCBjb21lcyBlcXVpcHBlZCB3aXRoIGEgPGEgaHJlZj0iaGFuZC5odG1sIj5oYW5kPC9hPiB2aWV3ZXIgdG8gcmVwbGFjZSBQb2tlclN0YXJzIHJlcGxheWVyCgkJPGxpPi4uLgoJPC91bD4KCQoJVGFibGVDcmFiIGRvZXMgbm90IGtub3cgbXVjaCBhYm91dCBQb2tlclN0YXJzIHRhYmxlcyBzbyB0byBtYWtlIFRhYmxlQ3JhYiB3b3JrIHlvdQoJaGF2ZSB0byBkZWZpbmUgdGFibGVzIG9uIHRoZSA8YSBocmVmPSJzZXR1cC5odG1sIj5zZXR1cDwvYT4gdGFiLiAKCQo8L2Rpdj4KCgo8ZGl2IGNsYXNzPSJ0ZXh0Qm94Ij4KCTxkaXYgY2xhc3M9ImhlYWRlckJveCI+U2VjdXJpdHk8L2Rpdj4KCQoJVGFibGVDcmFiIGRvZXMgbm90IGFjY2VzcyB0aGUgaW50ZXJuZXQuIHBvaW50LgoKPC9kaXY+CgoKCjwvYm9keT48L2h0bWw+Cg==")
		_cache["index"] = arr
	return QtCore.QString(arr)
def hotkeyScreenshot():
	arr = _cache.get("hotkeyScreenshot", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5Ib3RrZXkgU2NyZWVuc2hvdDwvZGl2PgoKCXdoZW5ldmVyIHlvdSBoaXQgdGhpcyBrZXkgeW91IGEgU2NyZWVuc2hvdCBvZiB0aGUgY3VycmVudCB3aWRnZXQgd2lsbCBiZSBkdW1wZWQgdG8gdGhlIHNjcmVlbnNob3Qgd2lkZ2V0IG9mIHRoZSA8YSBocmVmPSJzZXR1cC5odG1sIj5TZXR1cDwvYT4gdGFiLgoJCgk8ZGl2IGNsYXNzPSJub3RlQm94Ij4KCQk8dWw+CgkJPGxpPmxpbnV4IHVzZXJzOiB5b3UgY2FuIG9ubHkgdGFrZSBzY3JlZW5zaG90cyBvZiB3aWRnZXRzIGNvdHJvbGxlZCBieSB3aW5lLiBUYWJsZUNyYWIgaXMgYSB3aW5lIHdpZGdldCBhbmQgd2luZSB3aW5kZ2V0cyBkb24ndCBrbm93IGFueXRoaW5nIAoJCQkJYWJvdXQgdGhlIGxpbnV4IHRoZXkgYXJlIHJ1bm5pbmcgdXBvbgoJCTwvdWw+Cgk8L2Rpdj4KCjwvZGl2PgoKCjwvYm9keT48L2h0bWw+")
		_cache["hotkeyScreenshot"] = arr
	return QtCore.QString(arr)
def screenshotInfo():
	arr = _cache.get("screenshotInfo", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("c2NyZWVuc2hvdEluZm8=")
		_cache["screenshotInfo"] = arr
	return QtCore.QString(arr)
def hotkeyInstantHandHistory():
	arr = _cache.get("hotkeyInstantHandHistory", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("SG90a2V5SW5zdGFudEhhbmRIaXN0b3J5")
		_cache["hotkeyInstantHandHistory"] = arr
	return QtCore.QString(arr)
def setup():
	arr = _cache.get("setup", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5TZXR1cDwvZGl2PgoKCWFzIHNhaWQsIFRhYmxlQ3JhYiBkb2VzIG5vdCBrbm93IG11Y2ggYWJvdXQgdGFibGVzLiBpdCBkb2VzIG5vdCB0cnkgdG8gZ3Vlc3Mgd2hlcmUgYnV0dG9ucwoJb3IgY2hlY2tib3hlcyBhcmUuIGl0IGNhbiBvbmx5IHdvcmsgb24gZml4ZWQgc2l6ZWQgd2luZG93cyBhbmQgZml4ZWQgcG9zaXRpb25zLiBmb3IgdGhpcyB5b3UgCgloYXZlIHRvIHNldCB1cCB0ZW1wbGF0ZXMgZm9yLiAKCTxicj4KCTxicj4KCXRoZSBwcm9jZXNzIGlzIGZhaXJseSBzaW1wbGUuIGNyZWF0ZSBhIG5ldyB0ZW1wbGF0ZSBhbmQgc2l0IGF0IGEgdGFibGUuIGhpdCB0aGUgPGEgaHJlZj0iaG90a2V5U2NyZWVuc2hvdC5odG1sIj4KCXNjcmVlbnNob3Q8L2E+IGhvdGtleSB3aGVuIGJ1dHRvbnMgYmVjb21lIHZpc2libGUgYW5kIGdvIGJhY2sgdG8gdGhlIHNldHVwIHRhYi4gc2VsZWN0IHRoZSBidXR0b24gb3IgY2hlY2tib3ggCglpbiB0aGUgdGVtcGxhdGUgeW91IHdhbnQgdG8gYXNzaWduIGFuZCBkb3VibGUgY2xpY2sgdGhlIGNvcnJvc3BvbmRpbmcgY29ycm9zcG9uZGluZyBidXR0b24gb3IgY2hlY2tib3ggb24KCXRoZSBzY3JlZWVuc2hvdC4gdGhpcyB3aWxsIGZpbGwgaW4gdGhlIGxvY2F0aW9uIGluIHRoZSB0ZW1wbGF0ZS4geW91IG1heSBuZWVkIG1vcmUgdGhhbiBvbmUgc2NyZWVuc2hvdC4gYW5kIGl0J3MgYSAKCWdvb2QgaWRlYSB0byBzYXZlIHRoZW0gZm9yIGxhdGVyIHVzZS4KCgoJPGRpdiBjbGFzcz0ibm90ZUJveCI+CgkJPHVsPgoJCQk8bGk+dXNlIFBva2VyU3RhcnMgY3VzdG9tIGxheW91dHMgdG8gbWFrZSBzaHVyZSB5b3VyIHRhYmxlcyBhcmUgb2YgYSBmaXhlZCBzaXplIGJlY2F1c2UuLgoJCQk8bGk+YSB0ZW1wbGF0ZSB3aWxsIG9ubHkgd29yayBmb3IgYSB0YWJsZSBvZiBpdHMgc2l6ZQoJCQk8bGk+YnV0dG9ucyBvciBjaGVrYm94ZXMgd2l0aCBhIGxvY2F0aW9uIG9mICJOb25lIiB3aWxsIGJlIGlnbm9yZWQKCQkJCgkJPC91bD4KCQkKCQkKCQoJPC9kaXY+CgkKPC9kaXY+CgoKPGRpdiBjbGFzcz0idGV4dEJveCI+Cgk8ZGl2IGNsYXNzPSJoZWFkZXJCb3giPlRvb2xiYXI8L2Rpdj4KCgk8Yj5OZXc8L2I+Cgk8YnI+CgljcmVhdGVzIGEgbmV3IHRhYmxlIHRlbXBsYXRlLiBzZWxlY3QgdGhlIHRlbXBsYXRlIHlvdSB3YW50IHRvIGNyZWF0ZSBmcm9tIHRoZSBkcm9wZG93biBtZW51LgoJPGJyPgoJPGJyPgoJCgk8Yj5VcDwvYj4KCTxicj4KCW1vdmVzIHRoZSBjdXJyZW4gdGVtcGxhdGUgdXAuCgk8YnI+Cgk8YnI+CgkKCTxiPkRvd248L2I+Cgk8YnI+Cgltb3ZlcyB0aGUgY3VycmVuIHRlbXBsYXRlIGRvd24uCgk8YnI+Cgk8YnI+CgkKCTxiPlJlbW92ZTwvYj4KCTxicj4KCXJlbW92ZXMgdGhlIGN1cnJlbnQgdGVtcGxhdGUuCgk8YnI+Cgk8YnI+CgkKCTxiPlNhdmUgU2NyZWVuc2hvdC4uPC9iPgoJPGJyPgoJc2F2ZXMgdGhlIGN1cnJlbnQgc2NyZWVuc2hvdCB0byBmaWxlLgoJPGJyPgoJPGJyPgoJCgk8Yj5PcGVuIFNjcmVlbnNob3QuLjwvYj4KCTxicj4KCW9wZW5zIGEgc2NyZWVuc2hvdCBmcm9tIGZpbGUuCgk8YnI+Cgk8YnI+CgkKCTxiPkluZm8uLjwvYj4KCTxicj4KCW9wZW5zIGEgZGlhbG9nIHdpdGggZGV0YWlsZWQgaW5mbyBhYm91dCB0aGUgd2luZG93IHRoZSBzY3JlZW5zaG90IHdhcyB0YWtlbiBmcm9tLgoJPGJyPgoJPGJyPgoJCgkKPC9kaXY+CgoKPC9ib2R5PjwvaHRtbD4=")
		_cache["setup"] = arr
	return QtCore.QString(arr)
def settingsGlobal():
	arr = _cache.get("settingsGlobal", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5TZXR0aW5ncyBHbG9iYWw8L2Rpdj4KCgkKCTxiPkJhY2t1cCBUYWJsZUNyYWI8L2I+PGJyPgoJeW91IG1heSBiYWNrdXAgVGFibGVDcmFiIChhbGwgc2V0dGluZ3MsIGFsbCB0ZW1wbGF0ZXMsIGFsbCBob3RrZXlzIC4uLikgdG8KCWEgY29uZmlnIGZpbGUgb2YgeW91ciBjaG9pY2UuIHRoaXMgY29uZmlnIGZpbGUgbWF5IGJlIHBhc3NlZCB0byBUYWJsZUNyYWIKCWxhdGVyIGJ5IGFkZGluZyB0aGUgPGk+Ii0tY29uZmlnIjwvaT4gb3B0aW9uIHRvIHRoZSBjb21tYW5kbGluZS4gYW55IGNoYW5nZXMKCXRvIHRhYmxlQ3JhYiB3aWxsIGZyb20gdGhlbiBvbiBiZSBzdG9yZWQgaW4gdGhlIGZpbGUgeW91IHBhc3NlZC4KCTxicj4KCTxwcmU+Pj4gVGFibGVDcmFiLmV4ZSAtLWNvbmZpZyAiYzpcUGF0aFxUb1xZb3VyXFRhYmxlQ3JhYi5pbmkiPC9wcmU+Cgk8YnI+CgkKCTxiPkdsb2JhbCBTdHlsZTwvYj48YnI+CgloZXJlIHlvdSBtYXkgYWRqdXN0IHRoZSBvdmVyYWxsIGxvb2tzIG9mIFRhYmxlQ3JhYi4KCTxicj4KCTxicj4KCQoJPGI+R2xvYmFsIEZvbnQ8L2I+PGJyPgoJaGVyZSB5b3UgbWF5IGFkanVzdCB0aGUgZm9udCB0aGF0IFRhYmxlQ3JhYiB1c2VzLgoJPGJyPgoJPGJyPgoJCgk8Yj5ab29tIEluY3JlbWVudDwvYj48YnI+Cglzb21lIHdpZGdldHMgb2YgVGFibGVDcmFiIGFsbG93IGZvciB6b29taW5nIGluIGFuZCBvdXQuIHlvdSBtYXkgYWRqdXN0IHRoZQoJem9vbSBpbmNyZW1lbnQvZGVjcmVtZW50IGZhY3RvciBoZXJlLgoJPGJyPgoJPGJyPgoJCgk8Yj5Vc2UgQWx0ZXJuYXRpbmcgUm93IENvbG9yczwvYj48YnI+Cglzb21lIHdpZGdldHMgb2YgVGFibGVDcmFiIG1heSBzaG93IGFsdGVybmF0aW5nIHJvdyBjb2xvcnMuIGhlcmUgeW91IGNhbgoJdHVybiB0aGlzIGZlYXR1cmUgb24gb3Igb2ZmLgoJPGJyPgoJPGJyPgoJCgk8Yj5TaG93IENoaWxkIEl0ZW0gSW5kaWNhdG9yczwvYj48YnI+Cglzb21lIHRyZWUgd2lkZ2V0cyBvZiBUYWJsZUNyYWIgc2hvdyB0aGVzZSBsaXR0bGUgWytdWy1dIGJveGVzIGF0IHRoZSByb290IGl0ZW0uCglpZiB5b3UgZG9uJ3QgbGlrZSB0aGlzIHR1cm4gaXQgb2ZmIGhlcmUgKHRoZXkgY2FuIHN0aWxsIGJlIGV4cGFuZGVkL2NvbGxhcHNlZCBieSBoaXR0aW5nICIrIiBvciAiLSIgb24geW91ciBrZXlib2FyZCkuCgk8YnI+Cgk8YnI+CgkKCjwvZGl2PgoKCjwvYm9keT48L2h0bWw+")
		_cache["settingsGlobal"] = arr
	return QtCore.QString(arr)
def hotkeyCheck():
	arr = _cache.get("hotkeyCheck", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5Ib3RrZXkgQ2hlY2s8L2Rpdj4KCgl3aGVuZXZlciB5b3UgaGl0IHRoaXMga2V5IFRhYmxlQ3JhYiB3aWxsIGNoZWNrIHRoZSBoYW5kIGZvciB5b3UuIHRoYXQgaXMgLSBpdCBlaXRoZXIgaGl0cyB0aGUgPGk+IkNoZWNrIjwvaT4gYnV0dG9uIG9yIGNoZWNrcyB0aGUgPGk+IkNoZWNrL0ZvbGQiPC9pPiBjaGVja2JveC4KCQo8L2Rpdj4KCgo8L2JvZHk+PC9odG1sPg==")
		_cache["hotkeyCheck"] = arr
	return QtCore.QString(arr)
def settingsPokerStars():
	arr = _cache.get("settingsPokerStars", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("U2V0dGluZ3NQb2tlclN0YXJzCg==")
		_cache["settingsPokerStars"] = arr
	return QtCore.QString(arr)
def settings():
	arr = _cache.get("settings", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("U2V0dGluZ3MK")
		_cache["settings"] = arr
	return QtCore.QString(arr)
def hotkeyHilightBetAmount():
	arr = _cache.get("hotkeyHilightBetAmount", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("SG90a2V5SGlsaWdoQmV0QW1vdW50")
		_cache["hotkeyHilightBetAmount"] = arr
	return QtCore.QString(arr)
def settingsHandCss():
	arr = _cache.get("settingsHandCss", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("U2V0dGluZ3NIYW5kQ3NzCg==")
		_cache["settingsHandCss"] = arr
	return QtCore.QString(arr)
def hotkeyFold():
	arr = _cache.get("hotkeyFold", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("PGh0bWw+CjxoZWFkPgo8TElOSyBSRUw9U3R5bGVTaGVldCBIUkVGPSJkZWZhdWx0LmNzcyIgVFlQRT0idGV4dC9jc3MiIE1FRElBPXNjcmVlbj4KPC9oZWFkPgo8Ym9keT4KCjxkaXYgY2xhc3M9InRleHRCb3giPgoJPGRpdiBjbGFzcz0iaGVhZGVyQm94Ij5Ib3RrZXkgRm9sZDwvZGl2PgoKCXdoZW5ldmVyIHlvdSBoaXQgdGhpcyBrZXkgVGFibGVDcmFiIHdpbGwgZm9sZCB0aGUgaGFuZCBmb3IgeW91LiB0aGF0IGlzIC0gaXQgZWl0aGVyIGhpdHMgdGhlIDxpPiJGb2xkIjwvaT4gYnV0dG9uIG9yIGNoZWNrcyB0aGUgPGk+IkZvbGQiPC9pPiBjaGVja2JveC4KCQo8L2Rpdj4KCgo8L2JvZHk+PC9odG1sPg==")
		_cache["hotkeyFold"] = arr
	return QtCore.QString(arr)
