# auto generated resource file. WARNING: do not edit
from PyQt4 import QtCore
_cache = {}
def default():
	arr = _cache.get("default", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("CmJvZHl7Cglib3JkZXI6IHNvbGlkIGJsYWNrIDFweDsKCW1hcmdpbjogMGVtIDBlbSAwZW0gMGVtOwoJcGFkZGluZzogMC41ZW07Cgl9CgouYmFubmVyewoJbWFyZ2luLWJvdHRvbTogMWVtOwoJYmFja2dyb3VuZC1jb2xvcjogI0RFREVERTsKCWJvcmRlcjogc29saWQgYmxhY2sgMXB4OwoJZm9udC1zaXplOiB4LWxhcmdlOwoJfQouYmFubmVyVGV4dHsKCWJhY2tncm91bmQtY29sb3I6ICNERURFREU7Cgl0ZXh0LWFsaWduOiBjZW50ZXI7Cgl2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlOwoJfQoKCi5oZWFkZXJCb3h7CgliYWNrZ3JvdW5kLWNvbG9yOiAjQ0VERkYyOwoJYm9yZGVyOiBzb2xpZCAxcHg7CgltYXJnaW4tYm90dG9tOiAxZW07Cglmb250LXdlaWdodDogYm9sZDsKCXBhZGRpbmc6IDAuMmVtOwoJfQoudGV4dEJveHsKCWJhY2tncm91bmQtY29sb3I6ICNGQUZBRkE7Cglib3JkZXI6IHNvbGlkIGJsYWNrIDFweDsKCXBhZGRpbmc6IDAuNWVtOwoJfQoubm90ZUJveHsKCWJvcmRlcjogc29saWQgYmxhY2sgMXB4OwoJYmFja2dyb3VuZC1jb2xvcjogI0Y4RTVBNDsKCW1hcmdpbjogMWVtIDEwZW0gMWVtIDBlbTsKCXBhZGRpbmc6IDAuMmVtOwoJfQ==")
		_cache["default"] = arr
	return QtCore.QString(arr)
