# auto generated resource file. WARNING: do not edit
from PyQt4 import QtCore
_cache = {}
def default():
	arr = _cache.get("default", None)
	if arr is None:
		arr = QtCore.QByteArray.fromBase64("CmJvZHl7Cglib3JkZXI6IHNvbGlkIGJsYWNrIDFweDsKCW1hcmdpbjogMGVtIDBlbSAwZW0gMGVtOwoJcGFkZGluZzogMC41ZW07Cgl9CgouaGVhZGVyQm94ewoJYmFja2dyb3VuZC1jb2xvcjogI0NFREZGMjsKCWJvcmRlcjogc29saWQgMXB4OwoJbWFyZ2luLWJvdHRvbTogMWVtOwoJZm9udC13ZWlnaHQ6IGJvbGQ7CglwYWRkaW5nOiAwLjJlbTsKCX0KLnRleHRCb3h7CgliYWNrZ3JvdW5kLWNvbG9yOiAjRkFGQUZBOwoJYm9yZGVyOiBzb2xpZCBibGFjayAxcHg7CglwYWRkaW5nOiAwLjVlbTsKCX0KLm5vdGVCb3h7Cglib3JkZXI6IHNvbGlkIGJsYWNrIDFweDsKCWJhY2tncm91bmQtY29sb3I6ICNGOEU1QTQ7CgltYXJnaW46IDFlbSAyZW0gMWVtIDBlbTsKCXBhZGRpbmc6IDAuMmVtOwoJfQ==")
		_cache["default"] = arr
	return QtCore.QString(arr)
